# for zsh
ZSH=~/.oh-my-zsh
ZSH_THEME="qupeng"
DISABLE_AUTO_UPDATE="true"
CASE_SENSITIVE="true"
plugins=(git extract pip rustup rust cargo colored-man-pages)

ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
[[ ! -d $ZSH_CACHE_DIR ]] && mkdir $ZSH_CACHE_DIR

source $ZSH/oh-my-zsh.sh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
unsetopt AUTO_CD  # disable auto_cd when type dirname

# some binds
bindkey '^_[[Z' reverse-menu-complete

# env
export TERM="xterm-256color"

# some alias
alias rm="rm -i"
alias ls="ls -h --color=auto"
alias ll="ls -l"
alias cc="clear"
alias gg="exit"
alias vi="vim"

# alias for fucking too long systemctl
alias sc="systemctl"
alias scu="systemctl --user"

# for fg, bg, and history command
fg() {
	if [[ $# -eq 1 && $1 == - ]]; then
		builtin fg %-
	else
		builtin fg %"$@"
	fi
}

bg() {
	if [[ $# -eq 1 && $1 == - ]]; then
		builtin bg %-
	else
		builtin bg %"$@"
	fi
}
